name = "tn_julia"
uuid = "d46e0379-52b9-405d-b00f-50fb40aa6c6b"
authors = ["Simone.Fodera@lmu.de", "Ming.Huang@lmu.de", "O.Kovalska@lmu.de", "Ritter.Marc@lmu.de", "vondelft@lmu.de", "Changkai.Zhang@lmu.de"]
version = "25.0.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
BenchmarkTools = "1.6.0"
JLD2 = "0.5.13"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
Plots = "1.40.13"
Printf = "1.11.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
